# This is an example config with lots of comments


# Interfaces are defined here, you can have an arbitrary number
interfaces:
  image1:  # Interface name here, this is used in defining the respective mesh name
    type: image  # This maps to a dictionary that resolves to a particular interface class
    mesh_defs:  # Certain interfaces like nist have inputs and outputs so multiple definitions for meshes can be provided
      image1:  # This is the name of the mesh and should match the interface definition, this usually overlaps with the interface name
        static: False  # The interface instantiates the mesh definition and any options here overwrite the mesh def
        output_mesh_ids:
          - mesh3

  text_char:
    type: character
    source: "training_data/wordlist.10000"
    mesh_defs:
      text_char:
        ta: 20
        output_mesh_ids:
          - mesh3

meshes:
  mesh3:
    config:
      starting_ta: 20
      max_ta: 100


